SELECT it.ITEM_ID, it.ITEM_NAME, it.RARITY
FROM ITEM_INFO it JOIN ITEM_TREE tr on it.ITEM_ID = tr.ITEM_ID
WHERE tr.PARENT_ITEM_ID IN (
SELECT ITEM_ID
FROM ITEM_INFO
WHERE RARITY='RARE')
ORDER BY it.ITEM_ID DESC